doctrine:
    dbal:
        url: '%env(resolve:DATABASE_URL)%'

        # IMPORTANT: You MUST configure your server version,
        # either here or in the DATABASE_URL env var (see .env file)
        #server_version: '13'

        types:
            Height:
                class: App\Infrastructure\Persistence\Doctrine\DoctrineHeight
            Id:
                class: App\Infrastructure\Persistence\Doctrine\DoctrineId
    orm:
        auto_generate_proxy_classes: true
        naming_strategy: doctrine.orm.naming_strategy.underscore_number_aware
        auto_mapping: true
        mappings:
            Milestone:
                is_bundle: false
                type: xml
                dir: '%kernel.project_dir%/src/Infrastructure/Persistence/Doctrine'

                prefix: 'App\Domain'
                alias: Milestone
